FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*
    
# Copy from root directory
COPY requirements_producer.txt .
COPY streaming_simulator/producer.py .
COPY streaming_simulator/video.mp4 .

RUN pip install --no-cache-dir -r requirements_producer.txt

CMD ["python", "producer.py"]